
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main, develop, release" ]
  pull_request:
    branches: [ "main", "develop", "release" ]

  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test script
        run: |
          echo $GITHUB_ACTOR
          bash -n testscript.sh


  Run-script:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: test-script
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!